### ISSUE TITLE
import stdin, stdout fail

### ISSUE THREAD

**Issue by gasolin** [holepunchto/bare-process#1]
porting normal process code:

```js
const { stdin, stdout, exit } = process;
```

by set package alias in package.json:

```json
  "dependencies": {
    "bare-process": "^1.3.2"
  },
  "imports": {
    "process": {
      "bare": "bare-process",
      "default": "process"
    },
    "process/*": {
      "bare": "bare-process/*",
      "default": "process"
    }
  }
```

run in `pear dev` and see

```sh
❯ pear dev
2024-04-30T22:29:13.246Z cli exiting due to unhandled rejection
key=pqbzjhqyonxprx8hghxexnmctw75mr91ewqw5dxe1zmntfyaddqy
length=2774
fork=0
platform=darwin
arch=arm64
pid=61038
uptime=0.009s
stack=ReferenceError: process is not defined
    at pear://dev/index.js:1:33
    at Module._evaluate (file:///Users/X/Library/Application%20Support/Pear/by-dkey/7216eeac5c879a2ca1dcff14bb8c1ad47d188a8c17b13e66f36d354ea8bd3b28/3/boot.bundle/node_modules/bare-module/index.js:128:13)
    at Module._transform (file:///Users/X/Library/Application%20Support/Pear/by-dkey/7216eeac5c879a2ca1dcff14bb8c1ad47d188a8c17b13e66f36d354ea8bd3b28/3/boot.bundle/node_modules/bare-module/index.js:119:12)
    at Module.load (file:///Users/X/Library/Application%20Support/Pear/by-dkey/7216eeac5c879a2ca1dcff14bb8c1ad47d188a8c17b13e66f36d354ea8bd3b28/3/boot.bundle/node_modules/bare-module/index.js:327:19)
    at Crank.run (file:///Users/X/Library/Application%20Support/Pear/by-dkey/7216eeac5c879a2ca1dcff14bb8c1ad47d188a8c17b13e66f36d354ea8bd3b28/3/boot.bundle/ipc/crank.js:88:14)
    at async file:///Users/X/Library/Application%20Support/Pear/by-dkey/7216eeac5c879a2ca1dcff14bb8c1ad47d188a8c17b13e66f36d354ea8bd3b28/3/boot.bundle/cmd/iface.js:64:39
    at async run (file:///Users/X/Library/Application%20Support/Pear/by-dkey/7216eeac5c879a2ca1dcff14bb8c1ad47d188a8c17b13e66f36d354ea8bd3b28/3/boot.bundle/cmd/run.js:58:5)
    at async Cmd.run (file:///Users/X/Library/Application%20Support/Pear/by-dkey/7216eeac5c879a2ca1dcff14bb8c1ad47d188a8c17b13e66f36d354ea8bd3b28/3/boot.bundle/cmd/index.js:53:18)
    at async module.exports (file:///Users/X/Library/Application%20Support/Pear/by-dkey/7216eeac5c879a2ca1dcff14bb8c1ad47d188a8c17b13e66f36d354ea8bd3b28/3/boot.bundle/cmd/index.js:78:3)
    at async cli (file:///Users/X/Library/Application%20Support/Pear/by-dkey/7216eeac5c879a2ca1dcff14bb8c1ad47d188a8c17b13e66f36d354ea8bd3b28/3/boot.bundle/cli.js:12:3)


Error logged at /Users/X/Library/Application Support/Pear/by-dkey/7216eeac5c879a2ca1dcff14bb8c1ad47d188a8c17b13e66f36d354ea8bd3b28/3/cli.crash.log
```

If import with 

```js
import  { stdin, stdout, exit } from 'bare-process'
```

Nothing happens

```sh
❯ pear dev
(base)
```

**Comment by kasperisager** [comment]
There's no global `process` object, you'll need to define that yourself:

```js
global.process = require('bare-process')
```
